### ISSUE TITLE
Also capitalize container-title?

### ISSUE THREAD

**Issue by bwiernik** [Juris-M/propachi-upper#2]
Could the plugin be adapted to also capitalize the subtitles of `container-title` if a `container-title-short` variable is present?

**Comment by fbennett** [comment]
Finally got to this. The code is now there, but it won't actually do anything yet in Zotero or Juris-M.

Subtitles are identified by two things in combination: a delimiter in the title field; and a match between the title and subtitle field text for the portion of the title field preceding the delimiter. For container-title, the short form is an abbreviation, which won't satisfy those conditions.

I'll leave the extended code in place, but we'll need to discuss how this ought to work in a running client.

**Comment by bwiernik** [comment]
Would it be possible to parse a subtitle based on a {:container-title-short: Title} variable pulled from the Extra field?

**Comment by fbennett** [comment]
Good idea. I'm not sure, but I'll check soon.

**Comment by bwiernik** [comment]
This was apparently fixed in version 1.1.63:
https://github.com/Juris-M/citeproc-js/blob/ca3c83c82bca78289280b21521e2794194d0d8f5/CHANGES.txt

**Comment by fbennett** [comment]
Yep.
