### ISSUE TITLE
Signing

### ISSUE THREAD

**Issue by bwiernik** [Juris-M/propachi-upper#3]
Do you have plans to get the Propachi plugins and Bluebook signals signed to work with Stable Firefox?

**Comment by fbennett** [comment]
I'll submit them this weekend, and see what happens.

**Comment by fbennett** [comment]
Given what the Propachi plugins were originally meant for, though (rapid
field testing of new processor code), their utility will drop significantly
with the signing process. Can't be helped.

**Comment by bwiernik** [comment]
I might be mistaken, but since signing is now decoupled from review, I don't think the utility will be too strongly hit.

**Comment by fbennett** [comment]
Not severely, so long as Firefox don't pull the plug, so to speak, on a
subsequent review. It just adds steps to the release process, which will
slow things down a bit at this end.
